- .vscode/launch.json
- pnpm-lock.yaml
- rollup.config.js
> Fix build and run error

- package.json
- packages/vue-virtual-textdocument/src/utils.ts
- packages/vue-virtual-textdocument/test/baseline.spec.ts
- pnpm-lock.yaml
- test/support/helpers.ts
> test(baseline): fix baseline tests on windows

- readme.md
Repair invalid link on analyze package
> Repair analyze package link

- packages/typescript-plugin-vue/src/context.ts
- packages/typescript-plugin-vue/src/servers/routing.ts
- packages/typescript-plugin-vue/src/servers/template.ts
- packages/vue-virtual-textdocument/src/documents/VueTextDocument.ts
> fix: handle new .vue files

- packages/analyze/src/analyzers/ScriptBlockAnalyzer.ts
- packages/compiler-tsx/src/index.ts
- packages/compiler-tsx/test/render-tsx.spec.ts
> fix: declare types for _renderList helper

- packages/typecheck/bin/typecheck.js
> fix(typecheck): resolve containing .vue file

- packages/typecheck/src/index.ts
> fix: Cross Platform comparison of paths

- packages/typecheck/bin/typecheck.js
This allows you to filter results by file type regardless of the result format.
> Use `--vue` filter with `--json`

- .vscode/launch.json
- packages/analyze/src/project/detector/components.ts
- packages/compiler-tsx/src/index.ts
- packages/compiler-tsx/src/transforms/transformElement.ts
- packages/compiler-tsx/src/transforms/transformFor.ts
- packages/compiler-tsx/src/transforms/transformIf.ts
- packages/compiler-tsx/test/render-tsx.spec.ts
- packages/typescript-plugin-vue/src/features/goto/goto-script-definitions.ts
- packages/typescript-plugin-vue/src/helpers/utils.ts
- packages/typescript-plugin-vue/src/servers/template.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- pnpm-lock.yaml
- samples/feature-diagnostics/package.json
- samples/feature-diagnostics/src/NestedVIf.vue
- samples/feature-diagnostics/src/Slot.vue
- samples/feature-diagnostics/src/SlotType.vue
- samples/feature-diagnostics/src/SlotTypeUsage.tsx
- samples/feature-diagnostics/src/SlotTypeUsage.vue
- samples/feature-diagnostics/src/UsingRouter.vue
- samples/feature-diagnostics/src/VOn.vue
- samples/feature-diagnostics/src/components/WithEmits.vue
- test/baseline/diagnostics.spec.ts
- test/baseline/vue-as-module.spec.ts
> fix: transform structural directive at root or nested

- packages/analyze/src/analyzers/ScriptOptionsComponentsAnalyzer.ts
- packages/analyze/src/component.ts
- packages/shared/src/string.spec.ts
- packages/shared/src/string.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- samples/feature-diagnostics/src/NoErrors.vue
- samples/feature-diagnostics/src/components/Example.Pascal.Component.vue
- samples/feature-diagnostics/src/components/example-kebab-component.vue
- samples/feature-diagnostics/src/components/example_snake_component.vue
> fix: Handle mixed cases in file names

- packages/analyze/bin/analyze.js
- packages/analyze/package.json
- packages/analyze/src/analyzer.ts
- packages/analyze/src/component.ts
- packages/analyze/src/index.ts
- packages/analyze/src/output/vetur.ts
- packages/analyze/src/output/web-types.ts
- packages/shared/src/component.ts
- pnpm-lock.yaml
Run `npx @vuedx/analyze -f vetur` to get vetur types
fixes #100
> feat(analyze): add vetur and web-types output formats

- packages/typescript-plugin-vue/src/constants.ts
- packages/typescript-plugin-vue/src/helpers/utils.ts
- packages/typescript-plugin-vue/src/servers/routing.ts
- packages/typescript-plugin-vue/src/servers/template.ts
- packages/typescript-plugin-vue/src/servers/virtual.ts
- packages/typescript-plugin-vue/src/servers/vue.ts
- packages/vue-virtual-textdocument/src/documents/VueTextDocument.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- samples/feature-completions/src/SFC-Script.vue
- samples/feature-completions/src/SFC-ScriptSetup.vue
- samples/feature-completions/src/SFC-ScriptTemplate.vue
- samples/feature-completions/src/SFC-Template.vue
- samples/feature-diagnostics/src/FeatureSetup.vue
- test/baseline/completions.spec.ts
- test/support/helpers.ts
> feat: block completions in .vue files

- packages/compiler-tsx/src/index.ts
- packages/compiler-tsx/src/transforms/transformElement.ts
- packages/compiler-tsx/src/utils.ts
- packages/compiler-tsx/test/render-tsx.spec.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- samples/feature-diagnostics/src/JSON.vue
- test/baseline/diagnostics.spec.ts
> fix(#106): escape text JSX characters in plain text

- packages/compiler-tsx/src/index.ts
- packages/compiler-tsx/src/transforms/transformElement.ts
- packages/compiler-tsx/test/render-tsx.spec.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- test/baseline/diagnostics.spec.ts
> fix(#93): use inline type declaration for _renderSlot to handle possible undefined slot errors

- test/baseline/rename.spec.ts
- test/support/helpers.ts
> test(#80): rename identifiers in template that are exported from setup() fn

- packages/typescript-plugin-vue/src/context.ts
- packages/typescript-plugin-vue/src/helpers/utils.ts
- packages/typescript-plugin-vue/src/servers/vue.ts
- packages/vue-virtual-textdocument/src/documents/VueTextDocument.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- samples/feature-diagnostics/src/ChangeScriptLang.vue
- test/baseline/diagnostics.spec.ts
- test/support/TestServer.ts
> fix(#40): handle lang change on script block

- packages/compiler-tsx/src/index.ts
- packages/compiler-tsx/src/transforms/transformElement.ts
- packages/compiler-tsx/test/render-tsx.spec.ts
- packages/typescript-plugin-vue/src/features/completions/TemplateCompletionProvider.ts
- packages/vue-virtual-textdocument/test/__snapshots__/baseline.spec.ts.snap
- samples/feature-diagnostics/src/DynamicComponent.vue
- samples/feature-diagnostics/src/components/HelloWorld.vue
- test/baseline/diagnostics.spec.ts
- feat: support dynamic components using `<component is="...">`
- test: dynamic component render fn
fixes #114
> feat: support dynamic components

- .github/workflows/release.yaml
- extensions/coc-vue/package.json
- extensions/vscode-vue-language-features/package.json
- extensions/vscode-vue-language-features/readme.md
- extensions/vscode-vue/package.json
- package.json
- packages/analyze/analyze.api.md
- packages/analyze/package.json
- packages/analyze/readme.md
- packages/compiler-sfc/package.json
- packages/compiler-tsx/package.json
- packages/projectconfig/package.json
- packages/projectconfig/schema.json
- packages/shared/package.json
- packages/template-ast-types/package.json
- packages/template-ast-types/readme.md
- packages/template-ast-types/template-ast-types.api.md
- packages/typecheck/package.json
- packages/typescript-plugin-vue/package.json
- packages/typescript-standalone/package.json
- packages/typescript-vetur/package.json
- packages/vue-virtual-textdocument/package.json
- packages/vue-virtual-textdocument/readme.md
- packages/vue-virtual-textdocument/vue-virtual-textdocument.api.md
- pnpm-lock.yaml
- readme.md
- scripts/prepare-package.js
> release: initial public version

- extensions/coc-vue/package.json
- extensions/vscode-vue-language-features/package.json
- extensions/vscode-vue/package.json
- packages/analyze/package.json
- packages/compiler-sfc/package.json
- packages/compiler-tsx/package.json
- packages/projectconfig/package.json
- packages/shared/package.json
- packages/template-ast-types/package.json
- packages/typecheck/package.json
- packages/typescript-plugin-vue/package.json
- packages/typescript-standalone/package.json
- packages/typescript-vetur/package.json
- packages/vue-virtual-textdocument/package.json
> chore: remove unnecessary extension dependency

- packages/template-ast-types/src/stringify.ts
https://github.com/znck/vue-developer-experience/issues/176
> Processing comment code

- readme.md
https://github.com/znck/vue-developer-experience/pull/163
https://github.com/znck/vue-developer-experience/pull/164
https://github.com/znck/vue-developer-experience/pull/166
> README :warning: This package contains telemetry

- .changeset/rude-ads-worry.md
- CONTRIBUTING.md
- packages/transforms/src/index.ts
- packages/transforms/test/index.spec.ts
- packages/vue-languageservice/package.json
- packages/vue-languageservice/src/contracts/LanguageService.ts
- packages/vue-languageservice/src/features/CompletionsService.ts
- packages/vue-languageservice/src/features/CssLanguageService.ts
- packages/vue-languageservice/src/features/DefinitionService.ts
- packages/vue-languageservice/src/features/DiagnosticsService.ts
- packages/vue-languageservice/src/features/HtmlLanguageService.ts
- packages/vue-languageservice/src/features/QuickInfoService.ts
- packages/vue-languageservice/src/plugin.ts
- packages/vue-languageservice/src/services/AggregateLanguageService.ts
- packages/vue-languageservice/src/services/CacheService.ts
- packages/vue-languageservice/src/services/FilesystemService.ts
- packages/vue-languageservice/src/services/LanguageServiceProvider.ts
- packages/vue-languageservice/src/services/LoggerService.ts
- packages/vue-languageservice/src/services/TypescriptPluginService.ts
- packages/vue-virtual-textdocument/src/BlockTransformer.ts
- packages/vue-virtual-textdocument/src/VueBlockDocument.ts
- packages/vue-virtual-textdocument/src/index.ts
- packages/vue-virtual-textdocument/test/index.spec.ts
- pnpm-lock.yaml
- samples/vue3/typescript-diagnostics/src/ref.vue
- test/support/helpers.ts
- Goto Definition
- Goto Type Definition
> Implement definition service

- .changeset/tiny-guests-argue.md
- packages/vue-languageservice/src/features/RefactorService.ts
- packages/vue-languageservice/src/services/EncodedClassificationsService.ts
- packages/vue-languageservice/src/services/TypescriptContextService.ts
- packages/vue-languageservice/src/services/TypescriptPluginService.ts
> support organize imports

- .changeset/nasty-berries-pay.md
- packages/compiler-tsx/src/generate.ts
- packages/compiler-tsx/test/__snapshots__/baseline.js
- packages/compiler-tsx/test/__snapshots__/baseline.md
- packages/vue-languageservice/types/3.x.d.ts
- packages/vue-languageservice/types/shared/checkDirectiveOn.d.ts
- samples/vue3/typescript-diagnostics/src/v-model-checkbox.vue
- test/specs/diagnostics.spec.ts
> guard $event.target, $event.currentTarget and infer currentTarget type

- packages/shared/src/string.spec.ts
- packages/shared/src/string.ts
- packages/transforms/test/tsTransformScriptSetup.spec.ts
- packages/vue-language-server/src/fs.node.ts
- packages/vue-language-server/src/index.ts
- packages/vue-language-server/src/service.ts
- packages/vue-languageservice/package.json
- packages/vue-languageservice/src/VueProjectService.ts
- packages/vue-languageservice/src/VueTextDocument.spec.ts
- packages/vue-languageservice/src/index.ts
- packages/vue-languageservice/src/modes/LanguageModeHTML.spec.ts
- packages/vue-languageservice/src/modes/LanguageModeHTML.ts
- pnpm-lock.yaml
> Use snippets for block completion
